Product/urls.py
from django.urls import path
from django.contrib.auth import views
from .views import (BrandList,
                    CategoryList,
                    ProductList,
                    ProductDetail,
                    favourite_add,
                    favourite_list,
                    home,
                    )
app_name='product'
urlpatterns=[
    path('',ProductList.as_view(),name='home'),
    path('home/',home,name='homee'),
    path('product-detail/<slug:slug>',ProductDetail,name='detail'),
    path('category-product/<slug:slug>',CategoryList.as_view(),name='product_category'),
    path('category-product/<slug:slug>/page/<int:page>',CategoryList.as_view(),name='product_category'),
    path('fav/<int:id>',favourite_add,name='favourite_add'),
    path('favourite',favourite_list.as_view(),name='favourite_product'),
    path('favourite/page/<int:page>',favourite_list.as_view(),name='favourite_product'),

]

blog/urls.py
from django.urls import path
from .views import (ArticleList,
                    ArticleDetail,
                    ArticlePreview,
                    CategoryList,
                    AuthorList,
                    favourite_add,
                    favourite_list
                    )

app_name='blog'
urlpatterns = [
    path('', ArticleList.as_view(),name='home'),
    path('page/<int:page>', ArticleList.as_view(),name='home'),
    path('article/<int:pk>', ArticleDetail.as_view(),name='detail'),
    path('preview/<int:pk>', ArticlePreview.as_view(),name='preview'),
    path('category/<slug:slug>', CategoryList.as_view(),name='category'),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(),name='category'),
    path('author/<slug:username>', AuthorList.as_view(),name='author'),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(),name='author'),
    path('fav/<int:id>',favourite_add,name='favourite_add'),
    path('favourite',favourite_list.as_view(),name='favourite_list'),
    path('favourite/page/<int:page>',favourite_list,name='favourite_list'),
]

cart/urls.py
from django.urls import path,include,re_path
from .views import detail
from .views import CartAdd
app_name='cart'
urlpatterns = [
    path('',detail,name='detail'),
    path('add/<int:product_id>',CartAdd, name='cart-add')
]

config/urls.py
from django.contrib import admin
from dj_rest_auth.views import PasswordResetConfirmView
from django.urls import path,include,re_path
from account.views import Login,Register,activate
from rest_framework.authtoken.views import obtain_auth_token
# from rest_framework_simplejwt import views as jwt_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('',include('django.contrib.auth.urls')),
    path('cart/',include('cart.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('activate/<slug:uidb64>/<slug:token>/',activate, name='activate'),
    path('account/',include('account.urls')),
    path('comment/',include('comment.urls')),
    path('cart/',include('cart.urls'),name='cart'),
    path('product/',include('Product.urls')),
    # rest_url
    # path('api-auth/', include('rest_framework.urls')),
    # path('api/token-auth/', obtain_auth_token),
    # jwt
    # path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    # rest auth
    # path('api/rest-auth/', include('dj_rest_auth.urls')),
    # path('api/rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    # path('api/rest-auth/password/reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    # jwt djoser
    path('api/auth/', include('djoser.urls')),
    # path('api/auth/', include('djoser.urls.authtoken')),
    path('api/auth/', include('djoser.urls.jwt')),

    # api
    path('api/',include('Product_api.urls')),
    path('api/articles/',include('blog_api.urls')),
    path('api/dashbord/',include('account_api.urls')),

]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Product/models.py
from django.db import models
from django.urls.base import reverse
# from django.contrib.auth.models import User
from django.utils import  timezone
from extentions.utils import jalali_converter
from blog.models import Category
from account.models import User
# Create your models here.

class ProductManager(models.Manager):
    def published(self):
        return self.filter(status='p')
    def shose(self):
        return self.filter(type='shose')
    def pants(self):
        return self.filter(type='pants')
    def shirt(self):
        return self.filter(type='shirt')
    def headgear(self):
        return self.filter(type='headgear')
    def manto(self):
        return self.filter(type='manto')
    # def manto(self):
    #     return self.filter(seller='manto')

# class SpesialManager(models.Manager):
#     def shose(self):
#         return self.product.all()


class Brand(models.Model):
    thumbnail      =models.ImageField(upload_to='images',verbose_name='عکس',default=None)
    title      =models.CharField(max_length=200,verbose_name='نام برند')
    slug       =models.SlugField(unique=True,max_length=200,verbose_name='آدرس برن')
    employe    =models.ManyToManyField(User,related_name='brand',default=None,verbose_name='کارمند')
    description=models.TextField(verbose_name='توضیح')
    def get_absolute_url(self):
        return reverse('account:profile')
    # def employe_to_str(self):
    #     return 'و'.join([employe.email for employe in self.employe.allemp()])
        
class Product(models.Model):
    STATUS_CHOICES=(
        ('d','پیش نویس'),
        ('p','منتشر شده'),
    )
    STATUS=(
        ('shose','کفش'),
        ('pants','شلوار'),
        ('shirt','پیراهن'),
        ('headgear','روسری'),
        ('manto','مانتو'),
    )
    CHOICES=(
            ('red','قرمز'),
            ('blue','آبی'),
            ('yellow','زرد'),
            ('green','سبز'),
            ('black','سیاه'),
            ('gray','خاکستری'),
            ('white','سفید'),
            )
    CHOICES_GENDER=(
            ('male','مرد'),
            ('female','زن'),
            ('kid','کودک')
                        )
    category       =models.ManyToManyField(Category,related_name='product',verbose_name='دسته بندی محصول')
    thumbnail      =models.ImageField(upload_to='images',verbose_name='عکس',default=None)
    color          =models.CharField(max_length=10,choices=CHOICES,verbose_name='رنگ',default=None)
    title          =models.CharField(max_length=200,verbose_name='عنوان کالا')
    type           =models.CharField(max_length=10,choices=STATUS,verbose_name='نوع محصول',default=None)
    description    =models.TextField(verbose_name='توضیح')
    slug           =models.SlugField(unique=True,max_length=200,verbose_name='آدرس محصول')
    publish        =models.DateTimeField(default=timezone.now,verbose_name='زمان')
    created        =models.DateTimeField(auto_now_add=True,verbose_name='زمان ساخت')
    updated        =models.DateTimeField(auto_now=True,verbose_name='زمان آپدیت')
    status         =models.CharField(max_length=1,choices=STATUS_CHOICES,verbose_name='وضعیت')
    brand          =models.ForeignKey(Brand,on_delete=models.CASCADE,related_name='product',verbose_name='برند' ,default=None)
    seller         =models.ForeignKey(User,on_delete=models.CASCADE,related_name='product_seller',verbose_name='فروشنده' ,default=None)
    favourite      =models.ManyToManyField(User,related_name='favourite_product',default=None,blank=True,verbose_name='محصولات مورد علاقه ی شما')
    price          =models.DecimalField(max_digits=10,decimal_places=0,verbose_name='قیمت',default=0)
    gender         =models.CharField(max_length=7,choices=CHOICES_GENDER,verbose_name='جنسیت',default=None)
    class Meta:
        verbose_name="محصول"
        verbose_name_plural="محصولات"
        ordering=['-publish']
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('account:product-list')
    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description='زمان انتشار'
    def category_to_str(self):
        return 'و'.join([category.title for category in self.category.status_true()])
    objects=ProductManager()

class Special(models.Model):
    STATUS_CHOICES=(
        ('m','مدیوم'),
        ('l','لارج'),
        ('xl','ایکس لارج'),
        ('xxl','دو ایکس لارج'),
        ('xxxl','سه ایکس لارج'),
    )
    STATUS=(
        ('32','۳۲'),
        ('33','۳۳'),
        ('34','۳۴'),
        ('35','۳۵'),
        ('36','۳۶'),
        ('37','۳۷'),
        ('38','۳۸'),
        ('39','۳۹'),
        ('40','۴۰'),
        ('41','۴۱'),
        ('42','۴۲'),
        ('43','۴۳'),
        ('44','۴۴'),
        ('45','۴۵'),
        ('46','۴۶'),

    )
    sizepants       =models.CharField(max_length=4,choices=STATUS_CHOICES,verbose_name='سایز',null=True)
    sizeshose       =models.CharField(max_length=4,choices=STATUS,verbose_name='سایز',null=True)
    sizeshirt       =models.CharField(max_length=4,choices=STATUS_CHOICES,verbose_name='سایز',null=True)
    price          =models.DecimalField(max_digits=10,decimal_places=0,verbose_name='قیمت',default=0)
    count      =models.IntegerField(default=0,verbose_name='تعداد')
    seller_2         =models.ForeignKey(User,on_delete=models.CASCADE,related_name='seller_2',verbose_name='فروشنده' ,default=None)
    product    =models.ForeignKey(Product,related_name='product',on_delete=models.CASCADE,blank=True,default=None,verbose_name='محصولات')
    def get_absolute_url(self):
        return reverse('account:product-list')
    class Meta:
        unique_together=('sizepants','sizeshose','sizeshirt','seller_2')

Product/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import ListView,DeleteView,DetailView,UpdateView
from .models import Brand,Product,Special
from blog.models import Category,Article
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from cart.forms import CartAddForm
# Create your views here.
# @login_required
def favourite_add(request,id):
    product=get_object_or_404(Product.objects.published(),id=id)
    if product.favourite.filter(id=request.user.id):
        product.favourite.remove(request.user)
    else:
        product.favourite.add(request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])
class favourite_list(LoginRequiredMixin,ListView):
    template_name='Product/favourite.html'
    paginate_by=2
    def get_queryset(self):
        favourite=self.request.user
        product=Product.objects.filter(favourite=favourite)
        return product

def home(request):
    articles=Article.objects.published().order_by("-publish")[:9]
    context={
        'articles':articles,
    }
    return render(request,'Product/home.html',context)
class ProductList(ListView):
    # model=Article
    # template_name='blog/Home.html'
    context_object_name='products'
    queryset=Product.objects.published()
    paginate_by=2
def ProductDetail(request,slug):
    # Product.filter
    product=get_object_or_404(Product.objects.published(),slug=slug)
    product_like=Product.objects.filter(type=product.type)
    # product_like=Product.objects.raw('select * From Product where type=product.type')

    context={
    'product':product,
    'form':CartAddForm,
    'product_like':product_like
    }

    return render(request,'Product/product_detail.html',context)
# class ProductDetail(DetailView):
#     context_object_name='product'
#     template_name='Product/product_detail.html'
#     form_class=CartAddForm
#     def get_object(self):
#         slug=self.kwargs.get('slug')
#         return get_object_or_404(Product.objects.published(),slug=slug)


class CategoryList(ListView):
    paginate_by=2
    template_name='Product/category-product.html'
    def get_queryset(self):
        global category
        slug=self.kwargs.get('slug')
        category= get_object_or_404(Category.objects.status_true(),slug=slug)
        return category.product.published()
    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context['category']=category
        return context


class BrandList(ListView):
    template_name='blog/brand-product.html'
    paginate_by=2
    def get_queryset(self):
        global brand
        slug=self.kwargs.get('slug')
        brand= get_object_or_404(Brand,slug=slug)
        return brand.product.published()
    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context['category']=category
        return context

templates/Product/category-product.html
{% extends "Product/list.html" %}
{% block header_category %}
  <div>
    <h3 class=" text-center mt-1" style="background:gray;height: 3rem ;">
      {{category.title}}
    </h3>
  </div>
{% endblock %}
{% block paginator_prev %}
  {% url 'product:product_category' category.slug page_obj.previous_page_number %}
{% endblock %}
{% block paginator_next %}
  {% url 'product:product_category' category.slug page_obj.next_page_number %}
{% endblock %}

templates/Product/favourite.html
{% extends "blog/list.html" %}
{% block header_category %}
  <div>
    <h3 class=" text-center mt-1" style="background:gray;height: 3rem ;">
      محصولات مورد علاقه
    </h3>
  </div>
{% endblock %}
{% block paginator_prev %}
  {% url 'blog:favourite_list' page_obj.previous_page_number %}
{% endblock %}
{% block paginator_next %}
  {% url 'blog:favourite_list' page_obj.next_page_number %}
{% endblock %}

templates/Product/home.html
hello

templates/Product/list.html
{% extends "blog/base.html" %}
{% load static %}
{% block main %}
<header class="masthead" style="background-image: url('{% static 'blog/img/home-bg.jpg' %}')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>حجت</h1>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% block header_category %}

        {% endblock %}

        {% for product in object_list  %}
          <div class="post-preview">
            <a  href="{% url 'product:detail' product.slug %}">

              <div class="d-flex justify-content-end">
                <h3 class="post-subtitle" style="  font-size:1.5rem;font-weight: normal;">
                </h3>
                <img src="{{product.thumbnail.url}}" style="height:6rem ;width: 8rem; border-radius: 10%;" class="mr-3 ml-3" alt="">
                <h2 class="post-title  ">
                  {{product.title}}
                </h2>
              </div>
            </a>
            <div class="row">
              <p class="post-meta col-8 ">نوشته شده توسط:
                {# <a class="text-dark" href="{% url 'blog:author' product.author %}">{{product.author.get_full_name}}</a> #}
                {{product.jpublish}}
              </p>
              <div class="col-4 " style="padding-top:2rem" >

                {% for cat in product.category.status_true  %}
                  <a href="{%url 'product:product_category' cat.slug %}"> {{cat.title}}</a>
                {% endfor %}
              </div>
            </div>
            </div>
          <hr>

        {% endfor %}
        <!-- Pager -->
        {% if is_paginated %}
          <div class="clearfix row " style="justify-content: center;">
            {% if page_obj.has_previous %}
              <a class="btn  float-left " style="background-color:gray;color:white;border-radius: 5%;" href="{% block paginator_prev %}{% endblock %}"> پست یعدی  &rarr;</a>
            {% endif %}
            {% if page_obj.has_next %}
              <a class="btn  float-left ml-2 " style="background-color:gray;color:white;border-radius: 5%;" href=" {% block paginator_next %}{% endblock %}">پست  قبلی  &larr;</a>
            {% endif %}
          </div>
        {% endif %}
      </div>
    </div>
  </div>

{% endblock %}

templates/Product/product_detail.html
{% load static %}
{% load widget_tweaks %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'Product/bootstrap-rtl.css' %}">
    <link rel="stylesheet" href="{% static 'Product/style2.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container">

        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-4   col-md-6 col-sm-11 mt-5">
                <div class="card card-rooket" >
                    <div class="img-rook">

                        <img class=" img-rooket " src="{{product.thumbnail.url}}" alt="">
                    </div>
                    <div class="card-body  cs-card " >
                        <h5 class="card-title">{{product.title}}</h5>
                        <!-- <p card-text>طراح گرافیک از این متن به عنوان عنصری از ترکیب بندی برای پر کردن صفحه و ارایه اولیه شکل ظاهری و کلی طرح سفارش گرفته شده استفاده می نماید، تا از نظر گرافیکی نشانگر چگونگی نوع و اندازه فونت و ظاهر متن باشد. معمولا طراحان گرافیک </p> -->
                        <span class=" mx-3  mb-1">سایز:</span>
                        <div class="d-flex justify-content-between mx-5 ">
                            {% for sizee in product.sizeshose.all  %}
                            
                            <button class=" btn btn-light">{{sizee.count}}</button>
                            <button class=" btn btn-light">{{sizee.size}}</button>
                            {% endfor %}
                            
                            
                        </div>
                        
                        <span class=" mx-3 mt-3">رنگ:</span>
                        <div class="row mx-5 ">
                            <span class=" col-sm-2 ml-2 mt-2  cir-color cir-color1">{{product.color}}</span>
                            
                        </div>
                        
                        <div class="d-flex justify-content-between mx-3 mt-3">
                            <div> قیمت: 3000 تومان</div>
                            
                        </div>
                        <!-- <div class="d-flex justify-content-center mx-5 mt-3">
                        </div> -->
                        <form action="{% url 'cart:cart-add' product.id %}"method='Post'>
                            {% csrf_token %}
                            <button class="btn "  style="background: #607D8B; color: white;">افزودن به سبد خرید</button>
                            {{ form.quantity}}
                        </form>
                        <a href="{% url 'product:favourite_add' product.id %}" class="btn btn-info">مورد علاقه</a>
                    </div>

                    <!-- <div class="card-footer d-flex justify-content-between align-items-center ">
                        <div class="btn-grup mr-3">
                            <button class="btn btn-sm "  style="background: #9bdc28;">خرید</button>
                            <button class="btn btn-sm  btn-secondary mr-3" >نمایش</button>
                        </div>
                        <small class="badge badge-pill btn-warning">۹دقیقه</small>
                    </div> -->
                </div>
            </div>

        </div>
    </div>
  </body>
  </html>

templates/Product/product_list.html
{% extends "Product/list.html" %}

        {% block header_category %}
        {% endblock %}
        {% block paginator_prev %}
          {% url 'product:home' page_obj.previous_page_number %}
        {% endblock %}
        {% block paginator_next %}
          {% url 'product:home' page_obj.next_page_number %}
        {% endblock %}