blog/urls.py
from django.urls import path
from .views import (ArticleList,
                    ArticleDetail,
                    ArticlePreview,
                    CategoryList,
                    AuthorList,
                    favourite_add,
                    favourite_list
                    )

app_name='blog'
urlpatterns = [
    path('', ArticleList.as_view(),name='home'),
    path('page/<int:page>', ArticleList.as_view(),name='home'),
    path('article/<int:pk>', ArticleDetail.as_view(),name='detail'),
    path('preview/<int:pk>', ArticlePreview.as_view(),name='preview'),
    path('category/<slug:slug>', CategoryList.as_view(),name='category'),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(),name='category'),
    path('author/<slug:username>', AuthorList.as_view(),name='author'),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(),name='author'),
    path('fav/<int:id>',favourite_add,name='favourite_add'),
    path('favourite',favourite_list.as_view(),name='favourite_list'),
    path('favourite/page/<int:page>',favourite_list,name='favourite_list'),
]

config/urls.py
from django.contrib import admin
from dj_rest_auth.views import PasswordResetConfirmView
from django.urls import path,include,re_path
from account.views import Login,Register,activate
from rest_framework.authtoken.views import obtain_auth_token
# from rest_framework_simplejwt import views as jwt_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('',include('django.contrib.auth.urls')),
    path('cart/',include('cart.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('activate/<slug:uidb64>/<slug:token>/',activate, name='activate'),
    path('account/',include('account.urls')),
    path('comment/',include('comment.urls')),
    path('cart/',include('cart.urls'),name='cart'),
    path('product/',include('Product.urls')),
    # rest_url
    # path('api-auth/', include('rest_framework.urls')),
    # path('api/token-auth/', obtain_auth_token),
    # jwt
    # path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    # rest auth
    # path('api/rest-auth/', include('dj_rest_auth.urls')),
    # path('api/rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    # path('api/rest-auth/password/reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    # jwt djoser
    path('api/auth/', include('djoser.urls')),
    # path('api/auth/', include('djoser.urls.authtoken')),
    path('api/auth/', include('djoser.urls.jwt')),

    # api
    path('api/',include('Product_api.urls')),
    path('api/articles/',include('blog_api.urls')),
    path('api/dashbord/',include('account_api.urls')),

]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from account.models import User
from django.utils import  timezone
from extentions.utils import jalali_converter
from django.urls.base import reverse
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment
# my managers
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')
class CategoryManager(models.Manager):
    def status_true(self):
        return self.filter(status=True)
# Create your models here.
class Category(models.Model):
    parent=models.ForeignKey('self',default=None,null=True,blank=True,on_delete=models.SET_NULL,related_name='children',verbose_name='زیر دسته')
    title=models.CharField(max_length=200,verbose_name='عنوان دسته بندی')
    slug=models.SlugField(max_length=100,unique=True,verbose_name='آدرس دسته بندی')
    status=models.BooleanField(default=True,verbose_name="آیا ")
    position=models.IntegerField(verbose_name='وضعیت')
    class Meta:
        verbose_name="دسته"
        verbose_name_plural="دسته ها"
        ordering=['parent__id','position']
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('account:home')
    objects=CategoryManager()

class Article(models.Model):
    STATUS_CHOICES=(
        ('d','پیش نویس'),       #draft
        ('p','منتشر شده'),      #publish
        ('i','در حال برسی'),    #investigation
        ('b','برگشت داده شده'), #back
    )
    author=models.ForeignKey(User,null=True,on_delete=models.SET_NULL,related_name='article',verbose_name='نویسنده')
    category=models.ManyToManyField(Category,verbose_name='دسته بندی',related_name='article')
    favourite=models.ManyToManyField(User,related_name='article_fav',default=None,blank=True)
    title=models.CharField(max_length=200,verbose_name='عوان')
    slug=models.SlugField(max_length=100,unique=True,verbose_name='آدرس')
    description=models.TextField(verbose_name='متن')
    thumbnail=models.ImageField(upload_to='images',verbose_name='عکس',null=True)
    publish=models.DateTimeField(default=timezone.now,verbose_name='زمان')
    created=models.DateTimeField(auto_now_add=True,verbose_name='زمان ساخت')
    updated=models.DateTimeField(auto_now=True,verbose_name='زمان آپدیت')
    status=models.CharField(max_length=1,choices=STATUS_CHOICES,verbose_name='وضعیت')
    comments=GenericRelation(Comment)
    class Meta:
        verbose_name="مقاله"
        verbose_name_plural="مقالات"
        ordering=['-publish']
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('account:home')
    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description='زمان انتشار'
    def category_to_str(self):
        return ' و'.join([category.title for category in self.category.status_true()])
    category_to_str.short_description='دسته بندی ها'


    objects=ArticleManager()

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator
from account.models import User
from django.views.generic import ListView,DetailView,UpdateView
from account.mixins import ArticleUpdateAccessMixin
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Article,Category
# Create your views here.
@login_required
def favourite_add(request,id):
    article=get_object_or_404(Article.objects.published(),id=id)
    if article.favourite.filter(id=request.user.id).exists():
        article.favourite.remove(request.user)
    else:
        article.favourite.add(request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

class favourite_list(LoginRequiredMixin,ListView):
    paginate_by=3
    template_name='blog/favourite.html'
    def get_queryset(self):
        favourite=self.request.user
        article=Article.objects.filter(favourite=favourite)
        return article
class ArticleList(ListView):
    # model=Article
    # template_name='blog/Home.html'
    context_object_name='articles'
    queryset=Article.objects.published()
    paginate_by=2


# def Home(request,page=1):
#   articels_list=Article.objects.published()
#   paginator=Paginator(articels_list,2)
#   articels=paginator.get_page(page)
#   context={
#     'articles':articels
#   }
#   return render(request,'blog/Home.html',context)
class ArticleDetail(DetailView):
    def get_object(self):
        pk=self.kwargs.get('pk')
        return get_object_or_404(Article.objects.published(),pk=pk)
class ArticlePreview(ArticleUpdateAccessMixin,DetailView):
    def get_object(self):
        pk=self.kwargs.get('pk')
        return get_object_or_404(Article,pk=pk)
class CategoryList(ListView):
    template_name='blog/category.html'
    paginate_by=2
    def get_queryset(self):
        global category
        slug=self.kwargs.get('slug')
        category= get_object_or_404(Category.objects.status_true(),slug=slug)
        return category.article.published()
    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context['category']=category
        return context
class AuthorList(ListView):
    template_name='blog/author_list.html'
    paginate_by=2
    def get_queryset(self):
        global author
        username=self.kwargs.get('username')
        author= get_object_or_404(User,username=username)
        return author.article.published()
    # def get_context_data(self,**kwargs):
    #     context=super().get_context_data(**kwargs)
    #     context['author']=author
    #     return context
# comment

templates/blog/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'blog/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'blog/css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/about-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">This is what I do.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

templates/blog/article_detail.html
{% extends "blog/base.html" %}
{% load comment_tags %}

{% load static %}
{% block main %}
<header class="masthead" style="background-image: url('{{article.thumbnail.url}}')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1 style="margin-bottom:3rem">{{article.title}}</h1>
          <time>{{article.jpublish}}</time>
        </div>

      </div>
    </div>
  </div>
</header>
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto text-justify " style="direction:rtl">
        {{article.description|safe}}
        <hr>
        <a href="{% url 'blog:favourite_add' article.id %}" class="btn btn-outline-info mt-1">
          مورد علاقه
        </a>
        {% render_comments article request %}
        {% include_static  %}
        {% include_bootstrap  %}
      </div>
    </div>

  </div>
</article>





{% endblock %}

templates/blog/article_list.html
{% extends "blog/list.html" %}

        {% block header_category %}
        {% endblock %}
        {% block paginator_prev %}
          {% url 'blog:home' page_obj.previous_page_number %}
        {% endblock %}
        {% block paginator_next %}
          {% url 'blog:home' page_obj.next_page_number %}
        {% endblock %}

        

templates/blog/author_list.html
{% extends "blog/list.html" %}
{% block header_category %}
  <div>
    <h3 class=" text-center mt-1" style="background:gray;height: 3rem ;">
      {{ author.get_full_name }}
    </h3>
  </div>
{% endblock %}
{% block paginator_prev %}
  {% url 'blog:author' author.username page_obj.previous_page_number %}
{% endblock %}
{% block paginator_next %}
  {% url 'blog:author' author.username page_obj.next_page_number %}
{% endblock %}

templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>حجت {% block title %}

  {% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css'  %}"rel="stylesheet ">

  <!-- Custom fonts for this template -->
  <link href="{% static 'blog/vendor/fontawesome-free/css/all.min.css' %} " rel="stylesheet" type="text/css">

  <!-- Custom styles for this template -->
  <link href="{% static 'blog/css/clean-blog.min.css'  %} "rel="stylesheet">
  <link rel="stylesheet" href="{% static 'blog/css/rtl.css'  %}">
   <link rel="stylesheet" href="{% static 'blog/css/vazir.css'  %}">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
       {% category_navbar %}
      <a class="navbar-brand" href="{%url 'blog:home'%}">{% title %}</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
    </div>
  </nav>

  <!-- Page Header -->


  {% block main %}

  {% endblock %}
  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'blog/js/clean-blog.min.js' %}"></script>

</body>

</html>

templates/blog/category.html
{% extends "blog/list.html" %}
{% block header_category %}
  <div>
    <h3 class=" text-center mt-1" style="background:gray;height: 3rem ;">
      {{category.title}}
    </h3>
  </div>
{% endblock %}
{% block paginator_prev %}
  {% url 'blog:category' category.slug page_obj.previous_page_number %}
{% endblock %}
{% block paginator_next %}
  {% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

templates/blog/contact.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/contact-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Contact Me</h1>
            <span class="subheading">Have questions? I have answers.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
        <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
        <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
        <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
        <form name="sentMessage" id="contactForm" novalidate>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Name</label>
              <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Email Address</label>
              <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Phone Number</label>
              <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Message</label>
              <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br>
          <div id="success"></div>
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
        </form>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Contact Form JavaScript -->
  <script src="js/jqBootstrapValidation.js"></script>
  <script src="js/contact_me.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>

templates/blog/favourite.html
{% extends "blog/list.html" %}
{% block header_category %}
  <div>
    <h3 class=" text-center mt-1" style="background:gray;height: 3rem ;">
      مقالات مورد علاقه
    </h3>
  </div>
{% endblock %}
{% block paginator_prev %}
  {% url 'blog:favourite_list' page_obj.previous_page_number %}
{% endblock %}
{% block paginator_next %}
  {% url 'blog:favourite_list' page_obj.next_page_number %}
{% endblock %}

templates/blog/list.html
{% extends "blog/base.html" %}
{% load static %}
{% block main %}
<header class="masthead" style="background-image: url('{% static 'blog/img/home-bg.jpg' %}')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>حجت</h1>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% block header_category %}

        {% endblock %}
        <div class="row">


        {% for article in object_list  %}
        <div class="col-6">
          <a href="{%url 'blog:detail' article.pk %}">
          <div class="card ">
            <img class="card-img-top" src="{{article.thumbnail.url}}" >
            <h3 class="card-header">{{article.title}}</h3>
            <div class="card-body">
              <p class="card-text" style="font-size:.2 rem">{{article.description|striptags|truncatewords:10|safe }}</p>
              {% for cat in article.category.status_true  %}
              <a href="{%url 'blog:category' cat.slug %}"> {{cat.title}}#</a>
              {% endfor %}
            </div>
            <div class="card-footer">
              <p class="post-meta ">نوشته شده توسط:
                <a class="text-dark" href="{% url 'blog:author' article.author %}">{{article.author.get_full_name}}</a>
                {{article.jpublish}}
              </p>

            </div>
          </div>
          </a>
        </div>
        {% endfor %}
        </div>
        <!-- Pager -->
        {% if is_paginated %}
          <div class="clearfix row " style="justify-content: center;">
            {% if page_obj.has_previous %}
              <a class="btn  float-left " style="background-color:gray;color:white;border-radius: 5%;" href="{% block paginator_prev %}{% endblock %}"> پست یعدی  &rarr;</a>
            {% endif %}
            {% if page_obj.has_next %}
              <a class="btn  float-left ml-2 " style="background-color:gray;color:white;border-radius: 5%;" href=" {% block paginator_next %}{% endblock %}">پست  قبلی  &larr;</a>
            {% endif %}
          </div>
        {% endif %}
      </div>
    </div>
  </div>

{% endblock %}